language: ruby
addons:
 code_climate:
   repo_token: 4d2c1cec2a5ba5fd0cd09aa76d1bcb52854e12ace21660dbf65a36a59ba7a973
bundler_args: --without docs
rvm:
  - 1.8.7
  - 1.9.3

install: NOEXEC=skip rake travis:setup
script: bundle exec rake spec
