os:
  - osx

language: ruby

branches:
  only:
    - master
    - /.+-stable$/

addons:
 code_climate:
   repo_token: 4d2c1cec2a5ba5fd0cd09aa76d1bcb52854e12ace21660dbf65a36a59ba7a973

rvm:
  - 2.0.0
  - 2.3.4
  - 2.5.0

install:
  - brew install bzr
  - bundle install
  - git config --global user.name  'CI'
  - git config --global user.email 'CI@example.com'

